POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###


GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg


###

GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###

GET http://localhost:3000/tweets/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###

GET http://localhost:3000/tweets/4/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###

GET http://localhost:3000/tweets/4/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###

POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg
Content-Type: application/json 

{
   "tweet": "The Mornings..."
}

###

DELETE http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mg.48LlvQordGGCW-RVYi9tActryxfH11gB-jU1suJeYXg

###